# Generated by Django 5.1 on 2024-08-28 13:00

from django.db import migrations

def create_data(apps, schema_editor):
    Category = apps.get_model('slz', 'Category')
    Category(name="Statement",).save()

class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
