# Generated by Django 5.1 on 2024-08-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0002_slz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.TextField(default='adil', max_length=255),
            preserve_default=False,
        ),
    ]
