# Generated by Django 5.1 on 2024-08-28 14:15

from django.db import migrations


def create_data(apps, schema_editor):
    Post = apps.get_model('slz', 'Post')
    Post(title="first_post",
         body="this is the first post",
         author="adil",
         ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0003_remove_post_categories_post_author'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
