# Generated by Django 5.1 on 2024-09-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0005_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='release_date',
            field=models.DateField(),
        ),
    ]
