# Generated by Django 5.1 on 2024-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0007_post_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
