# Generated by Django 5.1 on 2024-10-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0010_remove_event_end_remove_event_start_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2020-10-04'),
            preserve_default=False,
        ),
    ]
