# Generated by Django 5.1 on 2024-10-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0012_alter_event_end_date_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
