# Generated by Django 5.1 on 2024-10-27 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0016_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='sequence',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
