# Generated by Django 5.1 on 2024-11-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0018_timelineevent_exlude_date_timelineevent_exlude_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelineevent',
            old_name='exlude_date',
            new_name='exclude_date',
        ),
        migrations.RenameField(
            model_name='timelineevent',
            old_name='exlude_month',
            new_name='exclude_month',
        ),
    ]
