# Generated by Django 5.1 on 2024-11-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0019_rename_exlude_date_timelineevent_exclude_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='release_date',
            field=models.DateField(default='2024-11-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sequence',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
