# Generated by Django 5.1 on 2024-11-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0021_post_cover_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_picture_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sequence',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
