# Generated by Django 5.1 on 2024-11-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0022_alter_post_cover_picture_url_alter_post_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
