# Generated by Django 5.1 on 2024-11-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0023_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
