# Generated by Django 5.1 on 2024-11-09 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0024_alter_post_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
