# Generated by Django 5.1 on 2024-11-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0026_alter_post_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('sequence', models.IntegerField(unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
