# Generated by Django 5.1 on 2024-11-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0027_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='release_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='sequence',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
