# Generated by Django 5.1 on 2024-12-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0029_alter_event_end_date_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
