# Generated by Django 5.1 on 2024-12-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0030_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='credit_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='exclude_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='exclude_month',
            field=models.BooleanField(default=False),
        ),
    ]
