# Generated by Django 5.1 on 2024-12-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0031_galleryimage_credit_to_galleryimage_exclude_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
