# Generated by Django 5.1 on 2024-12-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0032_post_is_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statement',
            name='release_date',
            field=models.DateField(default=False),
        ),
    ]
