# Generated by Django 5.1 on 2024-12-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0034_alter_statement_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='video_url',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
