# Generated by Django 5.1 on 2024-12-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0035_statement_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='is_video',
        ),
    ]
