# Generated by Django 5.1 on 2024-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0036_remove_statement_is_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('release_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
