# Generated by Django 5.1 on 2024-12-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0039_post_link_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
