# Generated by Django 5.1 on 2024-12-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0040_calltoaction_is_link_calltoaction_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
