# Generated by Django 5.1 on 2024-12-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0041_alter_calltoaction_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
