# Generated by Django 5.1 on 2025-01-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0043_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='affiliation',
            field=models.IntegerField(blank=True, choices=[(1, 'Student'), (2, 'Staff'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
