# Generated by Django 5.1 on 2025-01-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0044_alter_signup_affiliation_alter_signup_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
