# Generated by Django 5.1 on 2025-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0045_alter_signup_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
