# Generated by Django 5.1 on 2025-02-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0047_alter_statement_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(unique=True)),
                ('highlighted_words', models.TextField(max_length=100)),
                ('rest_of_text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
