# Generated by Django 5.1 on 2025-02-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0048_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
