# Generated by Django 5.1 on 2025-02-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0049_event_link_text_event_link_url_event_location_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
