# Generated by Django 5.1 on 2025-02-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slz', '0050_event_location_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_url',
        ),
    ]
