services:

  frontend:
    build: 
      context: ../
      dockerfile: ./slz-docker/frontend/Dockerfile
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt:ro
      - ./logs:/var/log/nginx/
    depends_on:
      - backend
      
  
  certbot:
    profiles: ["cert"]
    image: certbot/dns-route53:latest
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    env_file:
      - ./frontend/.env
    command: >-
          certonly --dry-run --dns-route53 --webroot-path=/var/www/certbot
          --email adilkhan49@hotmail.com --agree-tos 
          -d soasliberatedzone.org -d www.soasliberatedzone.org

  backend:
    build: 
      context: ../
      dockerfile: ./slz-docker/backend/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: mariadb
    volumes:
      - mariavol:/var/lib/mysql
      - ./db:/mnt
    ports:
      - "3307:3306"
    env_file:
      - ./db/.env

volumes:
  mariavol: